spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
      auto-index-creation: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-url: ${REDIRECT_URL}

  main:
    allow:
      circular-reference: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  frontend:
    url: ${APP_FRONTEND_URL}
